; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = wave_sniff_s3

[env:wave_sniff_s3]
platform = espressif32 @ ^6.9.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions_16mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_unflags = -DARDUINO_USB_MODE=1
build_flags =
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
lib_deps =
	moononournation/GFX Library for Arduino@1.5.9
	bblanchon/ArduinoJson@^7.0.0
	ESP32Async/AsyncTCP@^3.3.3
	ESP32Async/ESPAsyncWebServer@^3.6.0
build_src_filter = +<main.cpp>

[env:wave_sniff_s3_b]
platform = espressif32 @ ^6.9.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions_16mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_unflags = -DARDUINO_USB_MODE=1
build_flags =
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
	-DBOARD_1_47B
lib_deps =
	moononournation/GFX Library for Arduino@1.5.9
	bblanchon/ArduinoJson@^7.0.0
	ESP32Async/AsyncTCP@^3.3.3
	ESP32Async/ESPAsyncWebServer@^3.6.0
build_src_filter = +<main.cpp>
