[platformio]
default_envs = wave_sniff_s3

[common]
platform = espressif32 @ ^6.9.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions_16mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_unflags =
    -DARDUINO_USB_MODE=1
build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
    moononournation/GFX Library for Arduino@1.5.7
    bblanchon/ArduinoJson@^7.0.0
    me-no-dev/AsyncTCP@^1.1.1
    me-no-dev/ESPAsyncWebServer@^1.2.3
lib_extra_dirs = lib

[env:wave_sniff_s3]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
board_build.f_cpu = ${common.board_build.f_cpu}
board_build.f_flash = ${common.board_build.f_flash}
board_build.flash_mode = ${common.board_build.flash_mode}
board_build.arduino.memory_type = ${common.board_build.arduino.memory_type}
board_build.partitions = ${common.board_build.partitions}
board_upload.flash_size = ${common.board_upload.flash_size}
board_upload.maximum_size = ${common.board_upload.maximum_size}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags}
upload_speed = ${common.upload_speed}
monitor_speed = ${common.monitor_speed}
monitor_filters = ${common.monitor_filters}
lib_deps = ${common.lib_deps}
lib_extra_dirs = ${common.lib_extra_dirs}
build_src_filter = +<main_wifi.cpp>