[env:spoofer_c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
; If your C3 board has native USB-CDC (no UART chip), uncomment:
; build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
